Repository claudealdric/twitter-clone, pull requests merged in 2021-05, with the labels that each got.

#2 Add quality of life items for better onboarding
  README.md
  package.json
  yarn.lock
Labels: documentation, enhancement

#3 Add recommended project-level extensions
  .vscode/extensions.json
Labels: enhancement

#7 Fix Vercel deployment issues
  .vscode/settings.json
  client/src/components/auth/UserPage.tsx
  client/src/components/shared/Navbar.tsx
  client/src/pages/home/Feed.tsx
Labels: bug

#11 Create new user on user registration page
  api/package.json
  api/src/users/dtos/create-user.dto.ts
  api/src/users/user.entity.ts
  api/src/users/users.repository.ts
  api/src/users/users.service.ts
  client/src/api/index.ts
  client/src/components/auth/UserPage.tsx
  client/src/components/auth/components/UserForm.module.css
  client/src/components/auth/components/UserForm.tsx
  client/src/components/auth/components/UserFormBlurb.module.css
  client/src/components/auth/components/UserFormBlurb.tsx
  client/src/pages/auth/Login.module.css
  client/src/pages/auth/Login.tsx
  client/src/pages/auth/Register.module.css
  client/src/pages/auth/Register.tsx
  yarn.lock
Labels: enhancement

#18 Add user authorization to API
  api/package.json
  api/src/app.module.ts
  api/src/auth/auth.controller.spec.ts
  api/src/auth/auth.controller.ts
  api/src/auth/auth.module.ts
  api/src/auth/auth.service.spec.ts
  api/src/auth/auth.service.ts
  api/src/auth/dto/index.ts
  api/tsconfig.json
  client/yarn.lock
  yarn.lock
Labels: enhancement

#17 Tweets feed
  .gitignore
  client/src/components/shared/Navbar.module.css
  client/src/components/shared/Navbar.tsx
  client/src/images/feedbean.png
  client/src/pages/auth/Login.module.css
  client/src/pages/auth/Login.tsx
  client/src/pages/auth/Register.module.css
  client/src/pages/auth/Register.tsx
  client/src/pages/home/Feed.module.css
  client/src/pages/home/Feed.tsx
  client/src/pages/home/Profile.module.css
  client/src/pages/home/Profile.tsx
Labels: enhancement

#21 Authenticate user on login page
  .vscode/settings.json
  client/src/api/index.ts
  client/src/pages/auth/Login.tsx
Labels: enhancement

#22 Replace static user values
  client/package.json
  client/src/interfaces/index.ts
  client/src/pages/home/Profile.tsx
  yarn.lock
Labels: enhancement

#24 Store user data in Redux store
  .vscode/settings.json
  api/src/auth/auth.service.ts
  api/src/users/users.controller.ts
  api/src/users/users.service.ts
  client/src/App.tsx
  client/src/components/shared/Navbar.tsx
  client/src/data/slices/counter.slice.ts
  client/src/data/slices/user.slice.ts
  client/src/data/store.ts
  client/src/interfaces/index.ts
  client/src/pages/Test.tsx
  client/src/pages/auth/Login.tsx
  client/src/pages/home/Feed.tsx
  client/src/pages/home/Profile.tsx
  client/src/utils/history.ts
Labels: enhancement
